Formatting

diff --git a/bashpass b/bashpass
--- a/bashpass
+++ b/bashpass
@@ -7,39 +7,42 @@
 #     Needed for the `Copy` function.
 set -ef +x -o pipefail
 
-# Detect the user.
-# When the user is root exit out.
-if [[ "$UID" == 0 ]]; then
-   printf "You must run this as a normal user.\nCurrent user ID: %s %s\n" "${UID}" "$([[ "${UID}" -eq 0 ]] && printf "(root)")"
-   exit 13
-fi
+# Loads all the necessary configurations.
+LoadConfigurations(){
+   # Detect the config file.
+   configLocation="$HOME/.config/bashpass"
+   config="$configLocation/bashpass.conf"
 
-# Detect the config file.
-configLocation="$HOME/.config/bashpass"
-config="$configLocation/bashpass.conf"
+   [[ -f ${config} ]] || Kill "config file not found." "2"
 
-if [[ ! -f ${config} ]]; then
+   # Get the necessary configurations from the configuration file.
+   email="$(grep "email" "$config" | cut -d" " -f2)"
+   passLocation="$HOME/$(grep "location" "$config" | cut -d" " -f2)"
+   version="$(grep "version" "$config" | cut -d" " -f2)"
+   timer="$(grep "timer" "$config" | cut -d" " -f2)"
+   passLength="$(grep "length" "$config" | cut -d" " -f2)"
+}
+
+# Print out the error that occurred and exit (with the correct exit code) afterwards.
+Kill() {
    printf "\n"
-   printf "An error occurred: Config file not found."
+   printf "An error occurred: %s" "${1}"
    printf "\n"
-   exit 2
-fi
+   exit "${2}"
+}
 
-# Get the necessary configurations from the configuration file.
-email="$(grep "email" "$config" | cut -d" " -f2)"
-passLocation="$HOME/$(grep "location" "$config" | cut -d" " -f2)"
-version="$(grep "version" "$config" | cut -d" " -f2)"
-timer="$(grep "timer" "$config" | cut -d" " -f2)"
-passLength="$(grep "length" "$config" | cut -d" " -f2)"
-
-# Create the necessary directories/files if they doesn't exists
-mkdir -p "${passLocation}"
+# Return the latest version using the GitHub API.
+GetLatestVersion() {
+   curl --silent "https://api.github.com/repos/AntonVanAssche/BashPass/releases/latest" | # Get latest release from GitHub api
+   grep '"tag_name":' |                                            # Get tag line
+   sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
+}
 
 # Return all possible options/usages of BashPass. 
 Help() {
    cat << EOF
 BashPass version: ${version}
-A simple password manager written in Bash.
+A password manager written in Bash.
 
 bashpass [option] [name]                      - Basic command structure.
 
@@ -59,6 +62,46 @@ EOF
 # Return the current verion of BashPass.
 Version() {
    printf "BashPass version: %s" "${version}"
+}
+
+# Function to ask for a name.
+Name() {
+   name="${1}"
+   function=${2}
+
+   if [[ -z "${name}" ]]; then
+      printf "Enter the name of the password you want to %s: " "${function}"
+      read -r name
+   fi
+}
+
+# Check whether the given password exists.
+PasswordExists() {
+   name="${1}"
+
+   if [[ ! -f "${passLocation}/${name}.gpg" ]]; then
+      Kill "password '${name}' doesn't exist." "1"
+   fi
+}
+
+# Ask the user whether to overwrite an existing password or not.
+PasswordAlreadyExists() {
+   while [[ -f ${passLocation}/${name}.gpg ]]; do
+      printf "A password with the name %s already exists." "'${name}'"
+      printf "\n"
+      printf "Do you want to overwrite the existing password [y/N]: "
+      read -r overwrite
+      
+      case "${overwrite}" in
+         [Yy])
+            rm -rf "${passLocation}/${name}.gpg"
+            ;;
+         *)
+            printf "Enter a new name: "
+            read -r name
+            ;;
+      esac
+   done
 }
 
 # Ask the user whether he would like to generate a password or to enter one himself.
@@ -94,7 +137,7 @@ RandomPassword() {
 
          # Generate a password using '/dev/urandom'.
          # Call the 'tr' command to translate the password to a character set.
-         password=$(</dev/urandom tr -dc '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%*()?.,/+-abcdefghijklmnopqrstuvwxyz' | head -c "${length}"; echo "")
+         password=$(</dev/urandom tr -dc '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%*()?.,/+-abcdefghijklmnopqrstuvwxyz' | head -c "${length}"; printf "")
          ;;
    esac
 
@@ -102,61 +145,6 @@ RandomPassword() {
 
    # Write password to the 'password' file.
    printf "%s" "${password}" > "${passLocation}/${name}"
-}
-
-# Function to ask for a name.
-Name() {
-   name="${1}"
-   function=${2}
-
-   if [[ -z "${name}" ]]; then
-      printf "Enter the name of the password you want to %s: " "${function}"
-      read -r name
-   fi
-}
-
-# Print out the errors that occurred and exit (with the correct exit code) afterwards.
-Kill() {
-   printf "\n"
-   printf "An error occurred: %s" "${1}"
-   printf "\n"
-   exit "${2}"
-}
-
-# Check whether the given password exists.
-PasswordExists() {
-   name="${1}"
-
-   if [[ ! -f "${passLocation}/${name}.gpg" ]]; then
-      Kill "password '${name}' doesn't exist." "1"
-   fi
-}
-
-# Ask the user whether to overwrite an existing password or not.
-PasswordAlreadyExists() {
-   while [[ -f ${passLocation}/${name}.gpg ]]; do
-      printf "A password with the name %s already exists." "'${name}'"
-      printf "\n"
-      printf "Do you want to overwrite the existing password [y/N]: "
-      read -r overwrite
-      
-      case "${overwrite}" in
-         [Yy])
-            rm -rf "${passLocation}/${name}.gpg"
-            ;;
-         *)
-            printf "Enter a new name: "
-            read -r name
-            ;;
-      esac
-   done
-}
-
-# Return the latest version using the GitHub API.
-GetLatestVersion() {
-   curl --silent "https://api.github.com/repos/AntonVanAssche/BashPass/releases/latest" | # Get latest release from GitHub api
-   grep '"tag_name":' |                                            # Get tag line
-   sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
 }
 
 # Add a new password.
@@ -305,19 +293,29 @@ Sync() {
    esac
 }
 
-# Detect 'gpg'
-command -v gpg &> /dev/null || Kill "gpg is required" "127"
+Main() {
+   # Detect the user.
+   # When the user is root exit out.
+   [[ "$UID" == 0 ]] && Kill "permission denied" "13"
 
-# Ask the e-meil address to encrypt when it can't be found in the config file.
-if [[ -z ${email} ]]; then
-   printf "Enter the email address you created the gpg key with: "
-   read -r email
-   printf "email: %s" "${email}" >> "${config}"
-fi
+   # Load all the necessary configurations.
+   LoadConfigurations
+   
+   # Create the necessary directories if they doesn't exists.
+   mkdir -p "${passLocation}"
 
-function Main() {
-    # Show the user when a new version is availble. 
-    [[ "$(GetLatestVersion)" == "${version}" ]] || printf "There is a new version available.\n"
+   # Show the user when a new version is availble. 
+   [[ "$(GetLatestVersion)" == "${version}" ]] || printf "There is a new version available.\n"
+
+   # Detect 'gpg'
+   command -v gpg &> /dev/null || Kill "gpg is required" "127"
+
+   # Ask the e-email address to encrypt when it can't be found in the config file.
+   if [[ -z ${email} ]]; then
+      printf "Enter the email address you created the gpg key with: "
+      read -r email
+      printf "email: %s" "${email}" >> "${config}"
+   fi
 
    case "${1}" in
       "--help"| "-h") Help;;
@@ -333,7 +331,7 @@ function Main() {
    esac
 }
 
-# Check if an argument '$1' is given.
+# Check if an argument '${1}' is given.
 if [[ "${1}" ]]; then
    Main "${@}"
 else
