Add function to update a password

diff --git a/bashpass b/bashpass
--- a/bashpass
+++ b/bashpass
@@ -25,79 +25,145 @@ mkdir -p "${passLocation}" "${configLocation}"
 touch "${config}"
 
 function Help() {
-   printf "%s" "\
+   cat << EOF
 BashPass version: $version
-A basic password manager written in Bash.
+A simple password manager written in Bash.
 
-bashpass [ add|delete|show|list ] [name]
+bashpass [--add|--update|--delete|--show|--list] [name] - Basic commands
 
-help                - Show this help message.
-version             - Show the version number
-add     [name]      - Add a password.
-delete  [name]      - Delete a password.
-show    [name]      - Show a password.
-list                - List all password.
-"
+--help                                   - Show this help message.
+--version                                - Show the version number
+--add                             [name] - Add a password.
+--update                          [name] - Update a password.
+--delete                          [name] - Delete a password.
+--show                            [name] - Show a password.
+--list                                   - List all password.
+EOF
 }
 
 function Version() {
    printf "BashPass version: %s" "${version}"
 }
 
-function Add() {
-   name="$1"
+function RandomPassword() {
+   printf "Do you want to generate a password [Y/n]: "
+   read -re random
 
-   if [[ -z "$name" ]]; then
+   case "${random}" in
+      [Nn])
+         printf "Enter a password: "
+         read -res password1
+
+         printf "Enter the password again: "
+         read -res password2
+         
+         while [[ "${password1}" != "${password2}" ]]; do
+            printf "Passwords ditn't match, please try again: "
+            read -res password2
+         done
+
+         password=${password1}
+         ;;
+      *)
+         printf "Give the lenght of the password: "
+         read -re lenght
+
+         # Generate a password using '/dev/urandom'.
+         # Call the 'tr' command to translate the password to a character set.
+         password=$(LC_ALL=C tr -dc "${PASH_PATTERN:-_A-Z-a-z-0-9}" < /dev/urandom | dd ibs=1 obs=1 count="${PASH_LENGTH:-${lenght}}" 2>/dev/null)
+         ;;
+   esac
+
+   if [[ -z "$password" ]]; then
+      Kill "Failed to set a password"
+      exit 1
+   fi
+}
+
+# Function to print out errors and exit afterwards.
+function Kill() {
+   printf "\nA error occured: %s\n\n" "${1}"
+   Help
+   exit 1
+}
+
+function PasswordExists() {
+   while [[ -f ${passLocation}/${name}.gpg ]]; do
+      printf "A password with the name %s already exists." "'${name}'"
+      printf "\nDo you want to overwrite the existing password [y/N]: "
+      read -r overwrite
+      
+      case "${overwrite}" in
+         [Yy])
+            rm -rf ${passLocation}/${name}.gpg;;
+         *)
+            printf "Enter a new name: "
+            read -r name
+      esac
+   done
+}
+
+function Add() {
+   name="${1}"
+
+   if [[ -z "${name}" ]]; then
       printf "Enter a name: "
       read -r name
    fi
 
-   if [ -z "$name" ]; then
+   if [ -z "${name}" ]; then
       Kill "Failed to set a name"
-      exit 1
    fi
 
-   printf "Do you want to generate a password [Y/n]: "
-   read -r random
+   # Check if a password with the chosen name already exists.
+   PasswordExists
 
-   case "$random" in
-      [Nn])
-         printf "Enter a password: "
-         read -rs password1
-            
-         printf "\nEnter the password again: "
-         read -rs password2
+   # Ask if the user want to generate a random password.
+   RandomPassword
 
-         if [[ "$password1" != "$password2" ]]; then
-            Kill "The password didn't match"
-            exit 1
-         fi
-
-         password=$password1
-         ;;
-        *)
-         printf "Give the lenght of the password: "
-         read -r lenght
-
-         # Generate a password using '/dev/urandom'.
-         # Call the 'tr' command to translate the password to a character set.
-         password=$(LC_ALL=C tr -dc "${PASH_PATTERN:-_A-Z-a-z-0-9}" < /dev/urandom | dd ibs=1 obs=1 count="${PASH_LENGTH:-$lenght}" 2>/dev/null)
-         ;;
-   esac
-
-   if [ -z "$password" ]; then
-      Kill "Failed to set a password"
-      exit 1
-   fi
-
-   printf "%s" "$password" > "$name"
+   # Write password to the 'password' file.
+   printf "%s" "${password}" > "${passLocation}/${name}"
 
    # Encrypte the password file using gpg.
-   gpg --encrypt --output "$passLocation/$name.gpg" --recipient "$email" "$name"  &> /dev/null
+   gpg --encrypt --output "${passLocation}/${name}.gpg" --recipient "${email}" "${passLocation}/${name}"  &> /dev/null
 
-   printf "\nPassword %s saved" "'$name'"
+   printf "Password %s has been successfully saved" "'${name}'"
 
-   rm -rf "$name"
+   # Remove the Decrypted password file after reading
+   # to prevent the password from being leaked afterwards.
+   # ':?' to ensure this never expands to '/*'
+   rm -rf "${passLocation:?}/${name}"
+}
+
+function Update() {
+   name="${1}"
+
+   if [[ -z "${name}" ]]; then
+      printf "Enter the name of the password you want to update: "
+      read -r name
+   fi
+
+   # Decrypte the password file.
+   gpg --decrypt --output "${passLocation}/${name}" "${passLocation}/${name}.gpg" &> /dev/null
+
+   # Ask if the user want to generate a random password.
+   RandomPassword
+
+   # Write password to the 'password' file.
+   printf "%s" "${password}" > "${passLocation}/${name}"
+
+   # Remove the ecrypted password file to prevent gpg from asking to overwrite.
+   rm -rf "${passLocation:?}/${name}"
+
+   # Encrypte the password file using gpg.
+   gpg --encrypt --output "${passLocation}/${name}.gpg" --recipient "${email}" "${passLocation}/${name}"  &> /dev/null
+
+   printf "Password %s has successfully been updated" "'${name}'"
+
+   # Remove the Decrypted password file after reading
+   # to prevent the password from being leaked afterwards.
+   # ':?' to ensure this never expands to '/*'
+   rm -rf "${passLocation:?}/${name}"
 }
 
 function Delete() {
@@ -135,13 +201,6 @@ function List() {
    ls -1 "$passLocation"
 }
 
-# Function to print out errors and exit afterwards.
-function Kill() {
-   printf "A error occured: %s\n\n" "$1"
-   Help
-   exit 1
-}
-
 # Detect 'gpg'
 command -v gpg &> /dev/null || Kill "gpg is required"
 
@@ -156,7 +215,7 @@ case "$1" in
    "--help") Help;;
    "--version") Version;;
    "--add") Add "${2}";;
-   "--delete") Delete "$2";;
+   "--update") Update "${2}";;
    "--delete") Delete "${2}";;
    "--show") Show "${2}";;
    "--list") List;;
