Add more descriptive comments, in the way of why the is there

diff --git a/bashpass b/bashpass
--- a/bashpass
+++ b/bashpass
@@ -6,26 +6,47 @@ set +o xtrace   # Disable debug mode.
 set -o pipefail # Don't hide errors within pipes.
 
 # Current version.
-version="3.0"
+readonly VERSION="3.0"
 
-# Assign the path to the config file to the variable '${config}'.
+# Whenever an error occurs, we want to notify the user about it.
+# This is a basic function that wil print the corresponding error
+# message to stderr, and will exit with the given exit status.
+error_out() {
+    printf '\n'
+    printf 'An error occurred: %s' "${1}" >&2
+    printf '\n'
+    exit "${2}"
+}
+
+# Surprisingly, 'sleep' is an external program and not a Bash built-in.
+# So their is a small possibility that it is not installed on a system,
+# although it is very unlikely. We can use 'read' to replace the 'sleep'
+# command.
+sleep() {
+    read -rt "${1}" <> <(:) || :
+}
+
+# Wrapper for 'command -v' to avoid spamming '> /dev/null'.
+# It also protects against user aliasses and functions.
+has() {
+    command=$(command -v "${1}") 2> /dev/null || error_out "${1} is required" 127
+    [[ -x ${command} ]] || error_out "${1} is not an executable" 1
+}
+
+# Assign the path of the config file to the variable '${config}'.
 config_path="${HOME}/.config/bashpass"
 config="${config_path}/bashpass.conf"
 
 # Detect the config file.
-if [[ ! -f ${config} ]]; then
-    printf '\n'
-    printf 'An error occurred: config file not found.'
-    printf '\n'
-    exit 2
-fi
+[[ ! -f ${config} ]] && error_out "config file not found" 2
 
-# Simple function to get the setting '${1}' from the config file.
-# This basically replaces the '$(grep "setting" "${config}" | cut -d" " -f2)'.
-# It's also pure bash, which means that no sub shells are used.
+# Since we can not use external tool like 'grep' and 'cut' to ensure compatibility,
+# we need a way to retrieve the user's settings from their configuration file.
+# This function will read the file, and return the value once the requested setting
+# is found. It basically does the same as 'grep "setting" "${config}" | cut -d" " -f2',
+# but then with pure bash instead.
 get_setting() {
-    while read -r;
-    do
+    while read -r; do
         if [[ "${REPLY}" =~ ^${1} ]]; then
             printf '%s' "${REPLY#*: }"
             break
@@ -33,8 +54,10 @@ get_setting() {
     done < "${config}"
 }
 
-# Get the necessary configurations from the configuration file.
-# '|| :' To prevent the script from exiting if the variable is not found
+# Get the necessary configurations from the configuration file,
+# using the 'get_setting' function.
+# We require the use of '|| :' to prevent the script from exiting
+# if the key-value pair is not found in the config file.
 # (especially needed for the '${configured_email} variable').
 configured_email="$(get_setting 'email')" || :
 configured_key_id="$(get_setting 'keyID')" || :
@@ -43,39 +66,17 @@ configured_timer="$(get_setting 'timer')" || :
 configured_pass_length="$(get_setting 'length')" || :
 configured_git_repo="$(get_setting 'gitRepo')" || :
 
-# Print error message to stderr, and exit with the given exit status.
-error_out() {
-    printf '\n'
-    printf 'An error occurred: %s' "${1}" >&2
-    printf '\n'
-    exit "${2}"
-}
-
-# Surprisingly, `sleep` is an external program and not a Bash built-in.
-# So it is possible that it is not installed on a system, although it is very unlikely.
-# We can use `read` to replace the `sleep` command.
-sleep() {
-    read -rt "${1}" <> <(:) || :
-}
-
-# Wrapper for `command -v` to avoid spamming '> /dev/null'.
-# It also protects against user aliasses and functions.
-has() {
-    command=$(command -v "${1}") 2> /dev/null || error_out "${1} is required" 127
-    [[ -x ${command} ]] || error_out "${1} is not an executable" 1
-}
-
-# Return all possible options/usages of BashPass.
+# Print out all available options.
 help() {
     printf '%s' "\
-BashPass version: ${version}
+BashPass version: ${VERSION}
 A password manager written in Bash.
 
 bashpass [option] [name]                            - Basic command structure.
 
 Options:
 --help      or -h                                   - show this help message.
---version   or -v                                   - show the version number
+--VERSION   or -v                                   - show the VERSION number
 --list      or -l                                   - list all password.
 --add       or -a                            [name] - add a password.
 --update    or -u                            [name] - update a password.
@@ -90,9 +91,9 @@ synchronize command:
 "
 }
 
-# Return the current verion of BashPass.
+# Print out the current version.
 version() {
-    printf 'BashPass version: %s' "${version}"
+    printf 'BashPass version: %s' "${VERSION}"
     printf '\n'
 }
 
@@ -107,7 +108,9 @@ set_name() {
     fi
 }
 
-# Check whether the given password exists.
+# To prevent the user from making unnecessary operations on passwords that don't exist,
+# we can use this function to check if the password exists. If it doesn't, we will
+# notify the user about it, and exit the script.
 check_password_exists() {
     pass_name="${1}"
 
@@ -115,7 +118,12 @@ check_password_exists() {
         error_out "password '${pass_name}' doesn't exist." 1
 }
 
-# Ask the user whether he would like to generate a password or to enter one himself.
+# We want the user to be able to either enter a password, or generate a random one.
+# Here we prompt the user to choose between the two options. If the user chooses
+# to generate a random password, we will ask for the length of the password.
+# Otherwise we will ask the user to enter a password twice, to ensure that the
+# user didn't make a typo, if he/she does that, we will ask the user to enter
+# the password again until the passwords match.
 set_password() {
     printf 'Do you want to generate a password [Y/n]: '
     read -r random
@@ -146,9 +154,12 @@ set_password() {
 
             [[ -z ${pass_length} ]] && pass_length=${configured_pass_length}
 
-            # Generate a password using '/dev/urandom'.
-            # Call the 'tr' command to translate the password to a character set.
-            password=$(LC_ALL=C tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' < /dev/urandom | dd ibs=1 obs=1 count="${pass_length}" 2> /dev/null) || :
+            # To generate a random password, we need read random bytes from '/dev/urandom'.
+            # Using 'tr' we can then translate the random bytes to a character set we want.
+            # After that we can use 'dd' to only take the first ${pass_length} characters.
+            password=$(LC_ALL=C \
+                tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' < /dev/urandom | \
+                dd ibs=1 obs=1 count="${pass_length}" 2> /dev/null) || :
             ;;
     esac
 
@@ -159,15 +170,23 @@ set_password() {
     printf '%s' "${password}" > "${configured_pass_location}/${pass_name}"
 }
 
-# Add a new password.
+# The function encrypts the password using GnuPG and stores it in a file called '${name].gpg'
+# If a password with the same name already exists in the password directory, the user is
+# prompted to either overwrite the existing password or choose a different name for
+# the new password. The decrypted password file is removed after reading to prevent
+# the password from being leaked afterwards.
 add() {
-    # Ask for a name when no name was given using ${2}.
+    # If a name argument was not provided, prompt the user to enter one.
     set_name "${1}" "add"
 
+    # If we were not able to set a name, exit with an error.
     [[ -z "${pass_name}" ]] && error_out "failed to set a name" 1
 
-    # Check if a password with the chosen name already exists.
-    # If it does, ask the user whether he wants to overwrite it,
+    # Whenever we detect that a password with the same name already exists,
+    # we don't want to overwrite it straight away, because the user might
+    # have made a typo when entering the name, and we don't want to lose
+    # the password that was already saved.
+    # We will ask the user whether he wants to overwrite the existing password,
     # or whether he wants to choose a different name.
     while [[ -f ${configured_pass_location}/${pass_name}.gpg ]]; do
         printf 'A password with the name %s already exists.' "'${pass_name}'"
@@ -186,7 +205,7 @@ add() {
         esac
     done
 
-    # Ask if the user want to generate a random password.
+    # Ask the user whether he'd like to generate a random password.
     set_password
 
     # Encrypte the password file using gpg.
@@ -196,15 +215,19 @@ add() {
     printf 'Password %s has been successfully saved' "'${pass_name}'"
     printf '\n'
 
-    # Remove the Decrypted password file after reading
+    # Remove the plain text password file after encrypting it,
     # to prevent the password from being leaked afterwards.
-    # ':?' to ensure this never expands to '/*'
+    # We use ':?' to ensure this never expands to '/*'
     rm -rf "${configured_pass_location:?}/${pass_name}"
 }
 
-# update an existing password.
+# This function decrypts the password file, and will ask the user to enter a new password.
+# Afterward, the password file will be encrypted again, and the decrypted file will be
+# removed to prevent the password from being leaked afterwards. Just like we do in the
+# 'add' function.
 update() {
-    # Ask for a name when no name was given using ${2}.
+    # If a name argument was not provided, prompt the user to enter one.
+    # Afterward, we will check if the password exists or not.
     set_name "${1}" "update"
     check_password_exists "${pass_name}"
 
@@ -225,15 +248,18 @@ update() {
     printf 'Password %s has successfully been updated' "'${pass_name}'"
     printf '\n'
 
-    # Remove the Decrypted password file after reading
+    # Remove the plain text password file after encrypting it,
     # to prevent the password from being leaked afterwards.
-    # ':?' to ensure this never expands to '/*'
+    # We use ':?' to ensure this never expands to '/*'
     rm -rf "${configured_pass_location:?}/${pass_name}"
 }
 
-# delete an existing password.
+# This function will delete the password file with the given name.
+# Be careful when using this function, because it will delete the password
+# without asking for confirmation.
 delete() {
-    # Ask for a name when no name was given using ${2}.
+    # If a name argument was not provided, prompt the user to enter one.
+    # Afterward, we will check if the password exists or not.
     set_name "${1}" "delete"
     check_password_exists "${pass_name}"
 
@@ -242,21 +268,28 @@ delete() {
     printf '\n'
 }
 
-# Print the password that was given.
+# This function will decrypt the password file and show the password to the user.
+# Be aware that the password will be shown in plain text, and the terminal won't
+# be cleared afterwards, so other people might be able to see the password.
 show() {
     # Ask for a name when no name was given using ${2}.
     set_name "${1}" "show"
     check_password_exists "${pass_name}"
 
     # Decrypte the password file and show the password
-    printf 'Password: %s' "$(${gpg_command} --decrypt --quiet "${configured_pass_location}/${pass_name}.gpg")"
+    printf 'Password: %s' "$(${gpg_command} --decrypt \
+        --quiet "${configured_pass_location}/${pass_name}.gpg")"
     printf '\n'
 }
 
-# copy the password that was given to the clipboard.
-# Clear the clipboard afterwards.
+# This function will decrypt the password file and copy it to the clipboard.
+# We are able to use xclip, xsel or wl-copy to copy the password to the clipboard.
+# After the timer has expired, the password will be removed from the clipboard.
+# This is a security measure to prevent the password from being leaked, it also makes
+# this feature more secure than the 'show' function.
 copy() {
     # Detect 'xclip' (X11), 'xsel' (X11) or 'wl-copy' (Wayland).
+    # Determine which clipboard command to use.
     if command -v xclip &> /dev/null; then
         clipboard_command="xclip -selection clipboard"
     elif command -v xsel &> /dev/null; then
@@ -267,24 +300,28 @@ copy() {
         error_out "xclip, xsel, or wl-copy is required" 127
     fi
 
-    # Ask for a name when no name was given using ${2}.
+    # If a name argument was not provided, prompt the user to enter one.
+    # Afterward, we will check if the password exists or not.
     set_name "${1}" "copy"
     check_password_exists "${pass_name}"
 
     # Ignore terminal interrupts (CTRL+C).
+    # We do this to prevent the ability to kill the script while
+    # the password is still in the clipboard.
     trap '' INT
 
     # Decrypte the password file and copy it to the clipboard using xclip, xsel or wl-copy.
     # This WON'T show the password inside the terminal output.
-    if "${gpg_command}" --decrypt --quiet "${configured_pass_location}/${pass_name}.gpg" | ${clipboard_command}; then
+    if "${gpg_command}" --decrypt --quiet "${configured_pass_location}/${pass_name}.gpg" | \
+        ${clipboard_command}; then
         printf 'Password %s has been copied to the clipboard' "'${pass_name}'"
         printf '\n'
     else
         error_out "failed to copy password '${pass_name}' to the clipboard." 1
     fi
 
-    # Wait for the timer to end clear the clipboard.
-    # 'timer' can be changed in the config file.
+    # Wait for the timer to end, and then clear the clipboard.
+    # The duration ('timer') can be changed in the config file.
     sleep "${configured_timer}" || kill 0
 
     if command -v xclip &> /dev/null; then
@@ -299,12 +336,15 @@ copy() {
     printf '\n'
 }
 
-# Return a list of all the passwords that are stored on your machine.
+# This function will list out all the names of the password files.
 list() {
     # Enable globbing for only this function.
-    set +f
+    set +o noglob
 
-    # Print the list of all the passwords (without using the `ls` command).
+    # We have to use a for loop to loop through all the files in the directory.
+    # The downside of this is that it will output the absolute path to the file.
+    # Therefore we have to remove the path and the file extension, using variable
+    # substitution.
     for p in "${configured_pass_location}"/*.gpg; do
         # Remove the path to the file.
         p="${p##*/}"
@@ -317,7 +357,7 @@ list() {
     done
 
     # Disable globbing.
-    set -f
+    set -o noglob
 }
 
 # Upload or download encrypted password(s) to/from a git repository.
@@ -329,6 +369,11 @@ sync() {
     # Detect 'git'
     has "git"
 
+    # This feature may only work when the user has configured a git repository,
+    # and the password directory is indeed a git repository.
+    # The user can configure the URL to the git repository in the config file.
+    # To detect whether the password directory is a git repository we check
+    # whether the '.git' directory exists.
     [[ -z ${configured_git_repo} ]] && \
         error_out "URL to git repository not specified in config" 1
     [[ -d "${configured_pass_location}/.git/" ]] || \
@@ -345,7 +390,8 @@ sync() {
                 --work-tree="${configured_pass_location}" \
                 commit -m "synchronize passwords ($(printf '%(%d/%m/%Y)T at %(%T)T)')"
 
-            if git --git-dir="${configured_pass_location}/.git/" --work-tree="${configured_pass_location}" push; then
+            if git --git-dir="${configured_pass_location}/.git/" \
+                --work-tree="${configured_pass_location}" push; then
                 printf '\n'
                 printf 'Remote password(s) successfully synchronized with local.'
             else
@@ -353,7 +399,8 @@ sync() {
             fi
             ;;
         [Dd]ownload)
-            if git --git-dir="${configured_pass_location}/.git/" --work-tree="${configured_pass_location}" pull; then
+            if git --git-dir="${configured_pass_location}/.git/" \
+                --work-tree="${configured_pass_location}" pull; then
                 printf '\n'
                 printf 'Local password(s) successfully synchronized with remote.'
             else
@@ -371,8 +418,10 @@ sync() {
 }
 
 main() {
-    # Detect the user.
-    # When the user is root exit out.
+    # We only want non-root users to use BashPass.
+    # This is because BashPass uses GnuPG to encrypt the passwords,
+    # and GnuPG uses the user's home directory to store the keys.
+    # Therefore if the user is root, the keys will be stored in the root's home directory.
     [[ "${UID}" == 0 ]] && error_out "permission denied" 13
 
     # Create the necessary directories if they doesn't exists.
@@ -387,15 +436,21 @@ main() {
 
     has "${gpg_command}"
 
-    # Ask the GPG key ID to use for encrypting the password.
-    # It will only ask when the configured_key_id isn't found in the config file.
+    # A user can have multiple GnuPG keys located on their system,
+    # therefore is a good idea to ask for a specific key, by prompting
+    # the user to enter a key ID. Afterwards we can simpply append it to
+    # the configuration file to save it.
     if [[ -z ${configured_key_id} ]]; then
         printf 'Enter the key ID of the GPG key you want to use: '
         read -r key_id
         printf 'keyID: %s\n' "${key_id}" >> "${config}"
     fi
 
-    # Ask the e-email address to encrypt when it can't be found in the config file.
+    # GnuPG keys are generated using a e-mailaddress specified by the user.
+    # In order to encrypt our password files, we need this e-mailaddress,
+    # whenever BashPass can not find an e-mailaddress within the user's configuration
+    # file, it will prompt the user to enter one, and write it to the configuration file
+    # afterwards
     if [[ -z ${configured_email} ]]; then
         printf 'Enter the email address you created the gpg key with: '
         read -r email
